BEGIN;

-- Devices table: registered kiosks / scanners / kiosks
CREATE TABLE IF NOT EXISTS devices (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) DEFAULT 'kiosk',
  location JSONB DEFAULT '{}'::jsonb,
  api_key_hash TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  last_seen TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clock logs: events generated by devices or user apps
CREATE TABLE IF NOT EXISTS clock_logs (
  id SERIAL PRIMARY KEY,
  device_id INTEGER REFERENCES devices(id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(32) NOT NULL, -- clock_in | clock_out | break_start | break_end | manual_adjust
  method VARCHAR(32) DEFAULT 'qr', -- qr | pin | button | api
  client_event_id VARCHAR(255) UNIQUE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clock_logs_user_created_at ON clock_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clock_logs_device_created_at ON clock_logs (device_id, created_at DESC);

COMMIT;
